config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get "/logout", to: "sessions#destroy"
  get '/signup', to: 'users#new'

  resources :users, only: [:new, :index, :create]
  resources :posts, only: [:new, :index, :create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  VALIDATE_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :email, presence: true, length: { minimum: 5, maximum: 50 }, format: { with: VALIDATE_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 5, maximum: 20 }
  has_many :posts

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user, only: %i[new create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params_post)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  private

  def params_post
    params.require(:post).permit(:title, :body)
  end

  def require_user
    redirect_to signin_path unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      login_user(user)
      puts "you've been logged in "
      redirect_to posts_path
    else
      puts 'Error email or password not incorrect'
      redirect_to 'new'
    end
  end

  def destroy
    logout
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login_user(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def logout
    current_user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
    redirect_to root_path
  end

  def current_user
    if (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      @current_user = user if user&.authenticated?(cookies[:remember_token])
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>   
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<% if logged_in? %>
  <%= link_to  "Create a new post", new_post_path %>  | Or | <%= link_to "Log out", logout_path %>
<%else%>
  <%= link_to  "Login to create a new post", signin_path %>
<% end %>
<h1>All Posts</h1>
<%@posts.each do |p|%>
  <p>Titile: <%= p.body%></p>
  <p>Body: <%= p.body%></p>
  <br>
  <% if logged_in? %>
    <p>Created by: <%= p.user.name%></p>
    <br>
  <%else%>
    <%= link_to  "Login to See the post author", signin_path %> <br>
  <% end %>
  ____________________
<%end%>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <%if @post.errors.any?%>
    <%@post.errors.full_messages.each do |er|%>
    <p><%=er%></p>
    <%end%>
  <%end%>

  <%= f.label :title, "title:" %>
  <%= f.text_field :title %> <br>
  <%= f.label :body, "body:" %>
  <%= f.text_field :body %> <br>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><%=@post.title%></h1>
<h1><%=@post.body%></h1>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name, "name:" %>
  <%= f.text_field :name %>
  <%= f.label :email, "email:" %>
  <%= f.email_field :email %>
  <%= f.label :password, "password:" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation, "password_confirmation:" %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>
<p>Allready have an account ? <%= link_to  "Login here", signin_path %></p>